spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/petrobras
    username: ROOT
    password: ROOT
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration